### ISSUE TITLE
index.md

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AI-102-AIEngineer.zh-tw#1]
English:
Microsoft Azure subscription

Current Translation:
 Microsoft Azure 訂閱

Suggested Translation:
Microsoft Azure 訂用帳戶

Description:
Inconsistent translation. Global check Azure 訂閱

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by olprod** [comment]
![image](https://user-images.githubusercontent.com/16075726/180364387-4df6f086-3303-4f9f-8e78-20922b84cc0a.png)
