### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AI-102-AIEngineer.zh-tw#2]
English:
How should I use these files relative to the released MOC files?

Current Translation:
我該如何使用與相對於已釋放的 MOC 檔案之這些檔案？

Suggested Translation:
相對於已釋放的 MOC 檔案，我應該如何使用這些檔案？

Description:
Accuracy issue

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
Run bugfix tool and waiting for result.

**Comment by olprod** [comment]
![image](https://user-images.githubusercontent.com/16075726/180364278-ed37628a-fec5-46f1-84ad-c01ed81e84a6.png)
