### ISSUE TITLE
ALL FILES 

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AI-102-AIEngineer.zh-tw#40]
All files in image folder are untranslated yet

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
The Art Locfile in Blocked status, re-set in Prehandoff status, waiting for checkedIn. [ICMS QUERY](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=C%26E&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5GYWxzZTwvU0hSUD48U0FUTz5GYWxzZTwvU0FUTz48U0FMTz5UcnVlPC9TQUxPPjxRRT4%2bMjwvUUU%2bPFFUPj48UVIgSWQ9IjEiIENQSUQ9IjAiPkN1cnJlbnQ7RmlsZXM7SG9zdCBDb250ZW50IFN0b3JlO0VxdWFsO0xBQl9BSS0xMDI8L1FSPjxRUiBJZD0iMiIgQ1BJRD0iMCI%2bYW5kO0N1cnJlbnQ7TG9jRmlsZXM7TGFuZ3VhZ2U7RXF1YWw7Q2hpbmVzZSAoVHJhZGl0aW9uYWwpPC9RUj48UVIgSWQ9IjQiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0NvbnRlbnQgVHlwZTtFcXVhbDtBcnQ8L1FSPjwvUVQ%2bPFJHPjxHQz5OVUxMPC9HQz48L1JHPjwvVlBRPg%3d%3d)

**Comment by stonezy123** [comment]
The image file checkIn and translated.
https://github.com/MicrosoftLearning/AI-102-AIEngineer.zh-tw/tree/OLPRODLOC/Instructions/images
